export const regions = ["美国", "欧洲", "中国", "东南亚", "其他"] as const;
export type Region = (typeof regions)[number];
export type Stage = "ready" | "review" | "queued" | "handed" | "suppressed";
export type MailState =
  | "none"
  | "draft"
  | "accepted"
  | "replied"
  | "bounced"
  | "unknown"
  | "paused"
  | "unsubscribed";
export type Account = {
  id: string;
  name: string;
  legal: string;
  domain: string;
  region: Region;
  country: string;
  industry: string;
  tier: string;
  model: string;
  email: string;
  department: string;
  supermicro: "使用已证实" | "转售已证实" | "待核实";
  products: string[];
  stage: Stage;
  mail: MailState;
  score: number;
  summary: string;
  reason: string;
};

// Entirely synthetic fixtures. No customer records or actual email addresses.
export const accounts: Account[] = [
  {
    id: "LG-001",
    name: "Northline Compute",
    legal: "Northline Compute, Inc.（虚构）",
    domain: "northline.example",
    region: "美国",
    country: "美国",
    industry: "GPU 云 / AI 算力",
    tier: "1A",
    model: "终端使用方",
    email: "procurement@northline.example",
    department: "采购部门",
    supermicro: "使用已证实",
    products: ["GPU 服务器", "DRAM"],
    stage: "ready",
    mail: "none",
    score: 94,
    summary:
      "运营 GPU 集群与按需计算服务，示例技术页面展示 Supermicro 服务器。",
    reason:
      "示例基础设施页包含服务器品牌与部署场景；采购页提供供应商联系邮箱。",
  },
  {
    id: "LG-002",
    name: "Harbor Bare Metal",
    legal: "Harbor Bare Metal LLC（虚构）",
    domain: "harborbm.example",
    region: "美国",
    country: "美国",
    industry: "裸金属 / 独立服务器",
    tier: "1A",
    model: "终端使用方",
    email: "partners@harborbm.example",
    department: "商务合作",
    supermicro: "使用已证实",
    products: ["整机", "企业级 SSD"],
    stage: "ready",
    mail: "none",
    score: 89,
    summary: "提供独立服务器和裸金属服务，属于服务器资产的运营方。",
    reason: "示例硬件规格页有 Supermicro 型号，商务页公布合作邮箱。",
  },
  {
    id: "LG-003",
    name: "Cedar Regional Cloud",
    legal: "Cedar Regional Cloud, Inc.（虚构）",
    domain: "cedarcloud.example",
    region: "美国",
    country: "美国",
    industry: "区域云服务",
    tier: "1B",
    model: "终端使用方",
    email: "sales@cedarcloud.example",
    department: "销售入口 · 可转交",
    supermicro: "待核实",
    products: ["整机", "网卡"],
    stage: "ready",
    mail: "none",
    score: 68,
    summary: "经营区域 IaaS 服务，公开资料未说明服务器品牌。",
    reason:
      "具备基础设施运营场景；公开 sales 邮箱可作为初始联系与转交入口，不冒称采购联系人。",
  },
  {
    id: "LG-004",
    name: "Nordhaven Infrastructure",
    legal: "Nordhaven Infrastructure GmbH（虚构）",
    domain: "nordhaven.example",
    region: "欧洲",
    country: "德国",
    industry: "区域云服务",
    tier: "1A",
    model: "终端使用方",
    email: "vendors@nordhaven.example",
    department: "供应商合作",
    supermicro: "使用已证实",
    products: ["整机", "DRAM", "HDD"],
    stage: "ready",
    mail: "none",
    score: 92,
    summary: "面向企业提供基础设施托管及云计算，拥有自营硬件。",
    reason: "示例客户技术博客展示 Supermicro 部署；供应商入口已完成演示复核。",
  },
  {
    id: "LG-005",
    name: "Fenwick GPU Cloud",
    legal: "Fenwick GPU Cloud Ltd（虚构）",
    domain: "fenwickgpu.example",
    region: "欧洲",
    country: "英国",
    industry: "GPU 云 / AI 算力",
    tier: "1A",
    model: "终端使用方",
    email: "partners@fenwickgpu.example",
    department: "商务合作",
    supermicro: "使用已证实",
    products: ["GPU 服务器"],
    stage: "handed",
    mail: "accepted",
    score: 90,
    summary: "提供 GPU 云算力服务，是示例中的首封邮件交接账户。",
    reason: "示例厂商案例与客户官网均给出硬件使用线索。",
  },
  {
    id: "LG-006",
    name: "栖云算力",
    legal: "栖云算力科技有限公司（虚构）",
    domain: "qiyun.example",
    region: "中国",
    country: "中国",
    industry: "GPU 云 / AI 算力",
    tier: "1A",
    model: "终端使用方",
    email: "purchase@qiyun.example",
    department: "采购部门",
    supermicro: "使用已证实",
    products: ["GPU 服务器", "CPU"],
    stage: "ready",
    mail: "none",
    score: 88,
    summary: "提供企业算力及训练集群运营服务。",
    reason: "示例公开采购资料及联系页提供了品牌与邮箱来源。",
  },
  {
    id: "LG-007",
    name: "远洲金融科技",
    legal: "远洲金融科技有限公司（虚构）",
    domain: "yuanzhou.example",
    region: "中国",
    country: "中国",
    industry: "金融 / 企业 IT",
    tier: "1B",
    model: "终端使用方",
    email: "vendors@yuanzhou.example",
    department: "供应商准入",
    supermicro: "待核实",
    products: ["存储服务器", "企业级 SSD"],
    stage: "review",
    mail: "none",
    score: 73,
    summary: "面向自有金融业务运行企业 IT 基础设施。",
    reason: "供应商准入渠道公开，但硬件采购范围与联系政策需要复核。",
  },
  {
    id: "LG-008",
    name: "Straits Compute",
    legal: "Straits Compute Pte. Ltd.（虚构）",
    domain: "straitscompute.example",
    region: "东南亚",
    country: "新加坡",
    industry: "区域云服务",
    tier: "1A",
    model: "终端使用方",
    email: "sourcing@straitscompute.example",
    department: "采购部门",
    supermicro: "使用已证实",
    products: ["整机", "网卡"],
    stage: "handed",
    mail: "replied",
    score: 91,
    summary: "提供区域计算基础设施；示例中客户已回复，由 Aimail 跟踪。",
    reason: "示例官网架构页含 Supermicro 使用证据。",
  },
  {
    id: "LG-009",
    name: "Mekong Systems",
    legal: "Mekong Systems Co., Ltd.（虚构）",
    domain: "mekongsystems.example",
    region: "东南亚",
    country: "越南",
    industry: "行业系统集成",
    tier: "1C",
    model: "方案集成商",
    email: "partners@mekongsystems.example",
    department: "商务合作",
    supermicro: "待核实",
    products: ["整机", "存储服务器"],
    stage: "ready",
    mail: "none",
    score: 78,
    summary: "承接企业数据中心和行业集成项目，以整机及方案采购为主。",
    reason: "项目型采购归 Tier 1C，但其经营类型保持为方案集成商。",
  },
  {
    id: "LG-010",
    name: "Pacific Rack Supply",
    legal: "Pacific Rack Supply, Inc.（虚构）",
    domain: "pacificrack.example",
    region: "美国",
    country: "美国",
    industry: "服务器渠道",
    tier: "2A",
    model: "整机贸易商",
    email: "purchasing@pacificrack.example",
    department: "采购部门",
    supermicro: "转售已证实",
    products: ["整机", "CPU"],
    stage: "ready",
    mail: "none",
    score: 86,
    summary: "采购并转售多品牌机架服务器，拥有 Supermicro 产品目录。",
    reason: "目录只能证明售卖品牌，不能当作终端部署证据。",
  },
  {
    id: "LG-011",
    name: "Baltic Component Exchange",
    legal: "Baltic Component Exchange B.V.（虚构）",
    domain: "balticparts.example",
    region: "欧洲",
    country: "荷兰",
    industry: "配件贸易",
    tier: "2B",
    model: "配件贸易商",
    email: "buying@balticparts.example",
    department: "采购部门",
    supermicro: "待核实",
    products: ["DRAM", "企业级 SSD", "HDD"],
    stage: "suppressed",
    mail: "unsubscribed",
    score: 77,
    summary: "经营企业存储和内存配件；演示退订后不再进入交接名单。",
    reason: "历史排除记录优先于新采集结果。",
  },
  {
    id: "LG-012",
    name: "Southern Edge Hosting",
    legal: "Southern Edge Hosting Pty Ltd（虚构）",
    domain: "southernedge.example",
    region: "其他",
    country: "澳大利亚",
    industry: "裸金属 / 独立服务器",
    tier: "1B",
    model: "终端使用方",
    email: "procurement@southernedge.example",
    department: "采购部门",
    supermicro: "待核实",
    products: ["整机", "HDD"],
    stage: "handed",
    mail: "bounced",
    score: 72,
    summary: "运营独立服务器；示例首封出现硬退信，地址已阻止再次交接。",
    reason: "整机运营场景明确，当前邮箱需要重新核对。",
  },
];

export const stageInfo: Record<Stage, { label: string; color: string }> = {
  queued: { label: "待交接", color: "processing" },
  ready: { label: "可交接", color: "success" },
  review: { label: "待核验", color: "warning" },
  handed: { label: "已交接", color: "processing" },
  suppressed: { label: "已排除", color: "default" },
};
export const mailInfo: Record<MailState, { label: string; color: string }> = {
  none: { label: "未发起", color: "default" },
  draft: { label: "待审核草稿", color: "processing" },
  accepted: { label: "SMTP 已接受", color: "processing" },
  replied: { label: "已回复", color: "success" },
  bounced: { label: "硬退信 · 停止联系", color: "error" },
  unknown: { label: "发送结果待核对", color: "warning" },
  paused: { label: "已暂停", color: "default" },
  unsubscribed: { label: "已退订", color: "default" },
};
